compile:
	g++ -o SnakeGame/bin/SnakeGame SnakeGame/main.cpp SnakeGame/classes/Game.cpp SnakeGame/classes/Map.cpp SnakeGame/classes/Player.cpp SnakeGame/classes/Snake.cpp SnakeGame/classes/TailList.cpp SnakeGame/classes/Tails.cpp -lncurses
