compile:
	g++ -o bin/SnakeGame -I /Users/nickhall/projects/bs/cpp/random/cpp_stuff/snake_game/SnakeGame/classes SnakeGame/main.cpp SnakeGame/classes/Game.cpp SnakeGame/classes/Map.cpp SnakeGame/classes/Snake.cpp
